Vacilometro/Controllers/UsuarioController.cs
using ImageResizer;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vacilometro.Models;

namespace Vacilometro.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsuarioController : Controller
    {
        private readonly ApplicationDbContext _db = new ApplicationDbContext();

        public ActionResult Index()
        {
            List<Usuario> usuarios = _db.Usuarios.ToList();

            return View(usuarios);
        }

        public ActionResult Details(Guid id)
        {
            Usuario usuario = _db.Usuarios.Find(id);

            if (usuario == null)
                return HttpNotFound();

            return View(usuario);
        }

        public ActionResult Create()
        {
            ViewBag.EmpresaId = new SelectList(_db.Empresas, "Id", "Nome");
            ViewBag.GeneroId = new SelectList(_db.Generos, "Id", "Nome");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Usuario usuario, HttpPostedFileBase ImageFile)
        {
            usuario.Id = Guid.NewGuid();

            if (ImageFile != null)
            {
                string extension = Path.GetExtension(ImageFile.FileName);

                if (!(extension == ".jpg" || extension == ".png" || extension == ".jpeg"))
                {
                    ModelState.AddModelError("ImageError", $"Formato não aceito. Aceito somente formatos: jpg, jpeg e png");
                }
                else
                {
                    if (ModelState.ContainsKey("ImageError"))
                        ModelState["ImageError"].Errors.Clear();

                    string name = Path.GetFileName($"{usuario.Id.ToString()}.jpg");

                    string path = Path.Combine(Server.MapPath("~/Images/Avatar"), name);
                    ImageFile.SaveAs(path);

                    ResizeSettings resizeSetting = new ResizeSettings
                    {
                        Format = "jpg",
                        Width = 250,
                        Height = 250
                    };

                    ImageBuilder.Current.Build(path, path, resizeSetting);
                }
            }

            if (ModelState.IsValid)
            {
                try
                {
                    
                    _db.Usuarios.Add(usuario);
                    _db.SaveChanges();
                }
                catch (Exception ex)
                {
                    return View(usuario);
                }
                
                return RedirectToAction("Index");
            }

            ViewBag.EmpresaId = new SelectList(_db.Empresas, "Id", "Nome", usuario.EmpresaId);
            ViewBag.GeneroId = new SelectList(_db.Generos, "Id", "Nome", usuario.GeneroId);

            return View(usuario);
        }

        public ActionResult Edit(Guid id)
        {
            Usuario usuario = _db.Usuarios.Find(id);

            if (usuario == null)
                return HttpNotFound();

            ViewBag.EmpresaId = new SelectList(_db.Empresas, "Id", "Nome", usuario.EmpresaId);
            ViewBag.GeneroId = new SelectList(_db.Generos, "Id", "Nome", usuario.GeneroId);

            return View(usuario);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Usuario usuario, HttpPostedFileBase ImageFile)
        {
            if (ImageFile != null)
            {
                string extension = Path.GetExtension(ImageFile.FileName);

                if (!(extension == ".jpg" || extension == ".png" || extension == ".jpeg"))
                {
                    ModelState.AddModelError("ImageError", $"Formato não aceito. Aceito somente formatos: jpg, jpeg e png");
                }
                else
                {
                    if (ModelState.ContainsKey("ImageError"))
                        ModelState["ImageError"].Errors.Clear();

                    string name = Path.GetFileName($"{usuario.Id.ToString()}.jpg");

                    string path = Path.Combine(Server.MapPath("~/Images/Avatar"), name);
                    ImageFile.SaveAs(path);

                    ResizeSettings resizeSetting = new ResizeSettings
                    {
                        Format = "jpg",
                        Width = 250,
                        Height = 250
                    };

                    ImageBuilder.Current.Build(path, path, resizeSetting);
                }
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _db.Entry(usuario).State = EntityState.Modified;
                    _db.SaveChanges();
                }
                catch (Exception ex)
                {
                    ViewBag.EmpresaId = new SelectList(_db.Empresas, "Id", "Nome", usuario.EmpresaId);
                    ViewBag.GeneroId = new SelectList(_db.Generos, "Id", "Nome", usuario.GeneroId);

                    return View(usuario);
                }

                return RedirectToAction("Index");
            }

            ViewBag.EmpresaId = new SelectList(_db.Empresas, "Id", "Nome", usuario.EmpresaId);
            ViewBag.GeneroId = new SelectList(_db.Generos, "Id", "Nome", usuario.GeneroId);

            return View(usuario);
        }

        public ActionResult Delete(Guid id)
        {
            Usuario usuario = _db.Usuarios.Find(id);

            if (usuario == null)
                return HttpNotFound();

            return View(usuario);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Usuario usuario = _db.Usuarios.Find(id);

            try
            {
                _db.Usuarios.Remove(usuario);
                _db.SaveChanges();
            }
            catch (Exception ex)
            {
                ViewBag.EmpresaId = new SelectList(_db.Empresas, "Id", "Nome", usuario.EmpresaId);
                ViewBag.GeneroId = new SelectList(_db.Generos, "Id", "Nome", usuario.GeneroId);

                return View(usuario);
            }

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Vacilometro/Views/Usuario/Create.cshtml
@model Vacilometro.Models.Usuario

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Usuario", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Usuario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.EmpresaId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmpresaId", null, "selecione a empresa...", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmpresaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GeneroId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GeneroId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GeneroId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Celular, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-4 col-sm-6 col-xs-12">
                @Html.Label("Imagem", htmlAttributes: new { @class = "control-label" })
                <input type="file" name="ImageFile" class="form-control-file" id="ImageFile">
                @Html.ValidationMessage("ImageError", "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Vacilometro/Views/Usuario/Delete.cshtml
@model Vacilometro.Models.Usuario

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Empresa.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empresa.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Celular)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Celular)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Vacilometro/Views/Usuario/Details.cshtml
@model Vacilometro.Models.Usuario

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Empresa.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empresa.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Celular)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Celular)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Vacilometro/Views/Usuario/Edit.cshtml
@model Vacilometro.Models.Usuario

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Usuario", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Usuario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.UserId)

        <div class="form-group">
            @Html.LabelFor(model => model.EmpresaId, "EmpresaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmpresaId", null, "selecione a empresa...", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmpresaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GeneroId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GeneroId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GeneroId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Celular, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-row">
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 ">
                @Html.Label("Imagem", htmlAttributes: new { @class = "control-label" })
                <input type="file" name="ImageFile" class="form-control-file" id="ImageFile">
                @Html.ValidationMessage("ImageError", "", new { @class = "text-danger" })
            </div>
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                @Html.Label("Avatar Atual", htmlAttributes: new { @class = "control-label col-12" })
                <img src="@Url.Content("~/Images/Avatar/" + Model.Id.ToString() + ".jpg")" alt="Sem Imagem" style="padding:5px; box-shadow: 0px 5px 5px 0px rgba(50, 50, 50, 0.5)" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Vacilometro/Views/Usuario/Index.cshtml
@model IEnumerable<Vacilometro.Models.Usuario>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Empresa.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Celular)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Empresa.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Celular)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>